// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/homefeed.proto

package homefeed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HomeFeedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tweet      string      `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	UserDetail *UserDetail `protobuf:"bytes,2,opt,name=user_detail,json=userDetail,proto3" json:"user_detail,omitempty"`
}

func (x *HomeFeedResponse) Reset() {
	*x = HomeFeedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homefeed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeFeedResponse) ProtoMessage() {}

func (x *HomeFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homefeed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeFeedResponse.ProtoReflect.Descriptor instead.
func (*HomeFeedResponse) Descriptor() ([]byte, []int) {
	return file_proto_homefeed_proto_rawDescGZIP(), []int{0}
}

func (x *HomeFeedResponse) GetTweet() string {
	if x != nil {
		return x.Tweet
	}
	return ""
}

func (x *HomeFeedResponse) GetUserDetail() *UserDetail {
	if x != nil {
		return x.UserDetail
	}
	return nil
}

type UserDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName   string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfilePic string `protobuf:"bytes,3,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	IsVerified int32  `protobuf:"varint,4,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
}

func (x *UserDetail) Reset() {
	*x = UserDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homefeed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetail) ProtoMessage() {}

func (x *UserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homefeed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetail.ProtoReflect.Descriptor instead.
func (*UserDetail) Descriptor() ([]byte, []int) {
	return file_proto_homefeed_proto_rawDescGZIP(), []int{1}
}

func (x *UserDetail) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDetail) GetProfilePic() string {
	if x != nil {
		return x.ProfilePic
	}
	return ""
}

func (x *UserDetail) GetIsVerified() int32 {
	if x != nil {
		return x.IsVerified
	}
	return 0
}

type HomeFeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *HomeFeedRequest) Reset() {
	*x = HomeFeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_homefeed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeFeedRequest) ProtoMessage() {}

func (x *HomeFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_homefeed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeFeedRequest.ProtoReflect.Descriptor instead.
func (*HomeFeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_homefeed_proto_rawDescGZIP(), []int{2}
}

func (x *HomeFeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_homefeed_proto protoreflect.FileDescriptor

var file_proto_homefeed_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x66, 0x65, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x66, 0x65, 0x65, 0x64,
	0x22, 0x5f, 0x0a, 0x10, 0x48, 0x6f, 0x6d, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x77, 0x65, 0x65, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x22, 0x84, 0x01, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x69, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x73,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x2a, 0x0a, 0x0f, 0x48, 0x6f, 0x6d, 0x65,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x32, 0x56, 0x0a, 0x0f, 0x48, 0x6f, 0x6d, 0x65, 0x46, 0x65, 0x65, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x46,
	0x65, 0x65, 0x64, 0x12, 0x19, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x48,
	0x6f, 0x6d, 0x65, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x66, 0x65, 0x65, 0x64, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x46, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09,
	0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x66, 0x65, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_homefeed_proto_rawDescOnce sync.Once
	file_proto_homefeed_proto_rawDescData = file_proto_homefeed_proto_rawDesc
)

func file_proto_homefeed_proto_rawDescGZIP() []byte {
	file_proto_homefeed_proto_rawDescOnce.Do(func() {
		file_proto_homefeed_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_homefeed_proto_rawDescData)
	})
	return file_proto_homefeed_proto_rawDescData
}

var file_proto_homefeed_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_homefeed_proto_goTypes = []interface{}{
	(*HomeFeedResponse)(nil), // 0: homefeed.HomeFeedResponse
	(*UserDetail)(nil),       // 1: homefeed.UserDetail
	(*HomeFeedRequest)(nil),  // 2: homefeed.HomeFeedRequest
}
var file_proto_homefeed_proto_depIdxs = []int32{
	1, // 0: homefeed.HomeFeedResponse.user_detail:type_name -> homefeed.UserDetail
	2, // 1: homefeed.HomeFeedService.HomeFeed:input_type -> homefeed.HomeFeedRequest
	0, // 2: homefeed.HomeFeedService.HomeFeed:output_type -> homefeed.HomeFeedResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_homefeed_proto_init() }
func file_proto_homefeed_proto_init() {
	if File_proto_homefeed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_homefeed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeFeedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homefeed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_homefeed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeFeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_homefeed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_homefeed_proto_goTypes,
		DependencyIndexes: file_proto_homefeed_proto_depIdxs,
		MessageInfos:      file_proto_homefeed_proto_msgTypes,
	}.Build()
	File_proto_homefeed_proto = out.File
	file_proto_homefeed_proto_rawDesc = nil
	file_proto_homefeed_proto_goTypes = nil
	file_proto_homefeed_proto_depIdxs = nil
}
