# Server configurations
server:
  host: ""
  port: "3333"

# Database credentials
database:
  user: "postgres"
  pass: "postgres"
  ip: "localhost"
  port: "5432"
  name: "twitter"

# Ports
ports:
  rpcport: "4444"
  rpcip: ""

